network.host: 0.0.0.0
cluster.name: elasticsearch
discovery.type: single-node
configsync.config_path: /var/lib/elasticsearch/config
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
