version: "3"
services:
  fess01:
    image: ghcr.io/codelibs/fess:13.12.1
    container_name: fess01
    environment:
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
    ports:
      - "8080:8080"
    networks:
      - esnet
    depends_on:
      - es01
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  esnet:
    driver: bridge
